{% set name = "upliftml" %}
{% set version = "0.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/upliftml-{{ version }}.tar.gz
  sha256: 612cb7fa1d57c5f7cfce9cc8bd2b39dfdda4acccaace070c67751082b0707811

build:
  number: 0
  noarch: python
  script:
    # Removing pyproject.toml here due to pip bug
    - {{ PYTHON }} -c "__import__('os').unlink('pyproject.toml')"
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6
  run:
    - matplotlib-base >=3.4.0,<4.0.0
    - numpy >=1.20.1,<2.0.0
    - pandas >=1.2,<2.0
    - pydantic >=1.8,<2.0
    - python >=3.6
    - scikit-learn >=0.24,<0.25
    - seaborn >=0.11.1,<0.12.0

test:
  imports:
    - upliftml
    - upliftml.models
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bookingcom/upliftml
  summary: A Python package for uplift modeling with PySpark and H2O
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://upliftml.readthedocs.io/

extra:
  recipe-maintainers:
    - thewchan
